# # Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
# path: '/home/panyue/AL/data' #dataset root dir
# train : images/train #train images (relative to 'path')
# val: images/train #tval images (relative to 'path')

#Classes

# names:
#   0: airplane
#   1: helicopter
#   2: small-vehicle
#   3: large-vehicle
#   4: ship
#   5: container
#   6: storage-tank
#   7: swimming-pool
#   8: windmill
#   9: ignore


path:  '/home/yue/AL/data'
train: '/home/yue/AL/data/train'
val: '/home/yue/AL/data/val'

#test: (Complete path to dataset test folder)

#Classes
nc: 10 

#classes names
#replace all class names list with your classes names
names: ['airplane', 'helicopter', 'small-vehicle', 'large-vehicle', 'ship', 'container', 'storage-tank','swimming-pool', 'windmill', 'ignore']